1 creation compte form frontend
Obsywon/Escapade pull request #22
Opened 2023-11-20 18:00 UTC by Obsywon

Ajout validation e-mail et mot de passe
ajout de hooks pour gérer l'état des entrées d'e-mail et mdp
Ajout de base de tests CI/CD pour tester react native

2023-11-20 18:57 UTC, GaetanKorpys submitted a review, later dismissed

2023-11-22 15:17 UTC, GaetanKorpys requested changes
Modification .gitignore nécéssaire avant de merge.

2023-11-22 16:11 UTC, Obsywon commented
Modification .gitignore faite -- et les dossiers bin et obj devaient être retirés manuellement des fichiers tracked

2023-11-23 17:26 UTC, GaetanKorpys approved these changes

2023-11-23 20:37 UTC, merged